import type {
  AdminAuditLogSelect,
  AthleteMatchPointsSelect,
  AthleteSelect,
  ChampionshipSelect,
  CreditPackSelect,
  CreditTransactionSelect,
  FantasyTeamSelect,
  GameweekStandingSelect,
  LeagueMembershipSelect,
  LeagueSelect,
  LineupSelect,
  LineupSlotSelect,
  MatchSelect,
  OtpSelect,
  RosterSelect,
  SessionSelect,
  TournamentPairSelect,
  TournamentSelect,
  UserSelect,
  WalletSelect,
} from "./generated/models.js";

export const userSelector = {
  id: true,
  email: true,
  name: true,
  role: true,
  isVerified: true,
  isBlocked: true,
  createdAt: true,
  updatedAt: true,
} satisfies UserSelect;

export const userAuthSelector = {
  ...userSelector,
  passHash: true,
} satisfies UserSelect;

export const sessionSelector = {
  id: true,
  userId: true,
  userAgent: true,
  isRevoked: true,
  expiresAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies SessionSelect;

export const otpSelector = {
  id: true,
  userId: true,
  purpose: true,
  codeHash: true,
  expiresAt: true,
  createdAt: true,
} satisfies OtpSelect;

export const adminAuditLogSelector = {
  id: true,
  adminId: true,
  action: true,
  entity: true,
  entityId: true,
  before: true,
  after: true,
  reason: true,
  createdAt: true,
  updatedAt: true,
} satisfies AdminAuditLogSelect;

export const championshipSelector = {
  id: true,
  name: true,
  gender: true,
  seasonYear: true,
  createdAt: true,
  updatedAt: true,
} satisfies ChampionshipSelect;

export const athleteSelector = {
  id: true,
  firstName: true,
  lastName: true,
  gender: true,
  championshipId: true,
  pictureUrl: true,
  entryPoints: true,
  globalPoints: true,
  averageFantasyScore: true,
  fantacoinCost: true,
  createdAt: true,
  updatedAt: true,
} satisfies AthleteSelect;

export const tournamentSelector = {
  id: true,
  championshipId: true,
  location: true,
  startDate: true,
  endDate: true,
  status: true,
  lineupLockAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies TournamentSelect;

export const tournamentPairSelector = {
  id: true,
  tournamentId: true,
  athleteAId: true,
  athleteBId: true,
  entryStatus: true,
  seedRank: true,
  createdAt: true,
  updatedAt: true,
} satisfies TournamentPairSelect;

export const matchSelector = {
  id: true,
  tournamentId: true,
  round: true,
  pairAId: true,
  pairBId: true,
  scheduledAt: true,
  set1A: true,
  set1B: true,
  set2A: true,
  set2B: true,
  set3A: true,
  set3B: true,
  winnerPairId: true,
  status: true,
  isRetirement: true,
  createdAt: true,
  updatedAt: true,
} satisfies MatchSelect;

export const leagueSelector = {
  id: true,
  name: true,
  type: true,
  createdBy: true,
  isOfficial: true,
  championshipId: true,
  rankingMode: true,
  rosterSize: true,
  startersPerGameweek: true,
  initialBudget: true,
  isMarketEnabled: true,
  status: true,
  entryFee: true,
  createdAt: true,
  updatedAt: true,
} satisfies LeagueSelect;

export const leagueMembershipSelector = {
  id: true,
  leagueId: true,
  userId: true,
  createdAt: true,
  updatedAt: true,
} satisfies LeagueMembershipSelect;

export const fantasyTeamSelector = {
  id: true,
  leagueId: true,
  userId: true,
  name: true,
  fantacoinsRemaining: true,
  totalPoints: true,
  createdAt: true,
  updatedAt: true,
} satisfies FantasyTeamSelect;

export const rosterSelector = {
  id: true,
  fantasyTeamId: true,
  athleteId: true,
  purchasePrice: true,
  currentValue: true,
  acquiredAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies RosterSelect;

export const lineupSelector = {
  id: true,
  fantasyTeamId: true,
  tournamentId: true,
  isLocked: true,
  isAutoGenerated: true,
  lockedAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies LineupSelect;

export const lineupSlotSelector = {
  id: true,
  lineupId: true,
  athleteId: true,
  role: true,
  benchOrder: true,
  isSubstitutedIn: true,
  pointsScored: true,
  createdAt: true,
  updatedAt: true,
} satisfies LineupSlotSelect;

export const gameweekStandingSelector = {
  id: true,
  leagueId: true,
  fantasyTeamId: true,
  tournamentId: true,
  gameweekPoints: true,
  cumulativePoints: true,
  rank: true,
  createdAt: true,
  updatedAt: true,
} satisfies GameweekStandingSelect;

export const walletSelector = {
  id: true,
  userId: true,
  balance: true,
  createdAt: true,
  updatedAt: true,
} satisfies WalletSelect;

export const creditPackSelector = {
  id: true,
  name: true,
  credits: true,
  stripePriceId: true,
  isActive: true,
  createdAt: true,
  updatedAt: true,
} satisfies CreditPackSelect;

export const creditTransactionSelector = {
  id: true,
  walletId: true,
  type: true,
  source: true,
  amount: true,
  balanceAfter: true,
  meta: true,
  createdAt: true,
  updatedAt: true,
} satisfies CreditTransactionSelect;

export const athleteMatchPointsSelector = {
  id: true,
  matchId: true,
  athleteId: true,
  basePoints: true,
  bonusPoints: true,
  totalPoints: true,
  createdAt: true,
  updatedAt: true,
} satisfies AthleteMatchPointsSelect;

export const modelSelectors = {
  User: userSelector,
  Session: sessionSelector,
  Otp: otpSelector,
  AdminAuditLog: adminAuditLogSelector,
  Championship: championshipSelector,
  Athlete: athleteSelector,
  Tournament: tournamentSelector,
  TournamentPair: tournamentPairSelector,
  Match: matchSelector,
  League: leagueSelector,
  LeagueMembership: leagueMembershipSelector,
  FantasyTeam: fantasyTeamSelector,
  Roster: rosterSelector,
  Lineup: lineupSelector,
  LineupSlot: lineupSlotSelector,
  GameweekStanding: gameweekStandingSelector,
  Wallet: walletSelector,
  CreditPack: creditPackSelector,
  CreditTransaction: creditTransactionSelector,
  AthleteMatchPoints: athleteMatchPointsSelector,
} as const;
